// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyMJag5k07ZTPQLCJZxchrqDZzt4xjEiA',
    appId: '1:726464864566:web:3f67cb2b748b5317931397',
    messagingSenderId: '726464864566',
    projectId: 'burpeebata',
    authDomain: 'burpeebata.firebaseapp.com',
    storageBucket: 'burpeebata.firebasestorage.app',
    measurementId: 'G-88KPSLSJP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwMuIejR4uFtFhi0oSM9FRoj8yJ8GrYQE',
    appId: '1:726464864566:android:6d06c460175d3fbb931397',
    messagingSenderId: '726464864566',
    projectId: 'burpeebata',
    storageBucket: 'burpeebata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyMJag5k07ZTPQLCJZxchrqDZzt4xjEiA',
    appId: '1:726464864566:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '726464864566',
    projectId: 'burpeebata',
    storageBucket: 'burpeebata.firebasestorage.app',
    iosBundleId: 'com.burpeebata.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyMJag5k07ZTPQLCJZxchrqDZzt4xjEiA',
    appId: '1:726464864566:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '726464864566',
    projectId: 'burpeebata',
    storageBucket: 'burpeebata.firebasestorage.app',
    iosBundleId: 'com.burpeebata.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyMJag5k07ZTPQLCJZxchrqDZzt4xjEiA',
    appId: '1:726464864566:web:3f67cb2b748b5317931397',
    messagingSenderId: '726464864566',
    projectId: 'burpeebata',
    authDomain: 'burpeebata.firebaseapp.com',
    storageBucket: 'burpeebata.firebasestorage.app',
    measurementId: 'G-88KPSLSJP2',
  );
}
