// Mocks generated by Mockito 5.4.0 from annotations
// in burpeebata/test/screens/timer_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i5;

import 'package:burpeebata/models/workout_config.dart' as _i4;
import 'package:burpeebata/services/timer_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TimerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimerService extends _i1.Mock implements _i2.TimerService {
  MockTimerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TimerState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i2.TimerState.idle,
      ) as _i2.TimerState);

  @override
  int get currentSeconds => (super.noSuchMethod(
        Invocation.getter(#currentSeconds),
        returnValue: 0,
      ) as int);

  @override
  int get currentSet => (super.noSuchMethod(
        Invocation.getter(#currentSet),
        returnValue: 0,
      ) as int);

  @override
  int get totalSets => (super.noSuchMethod(
        Invocation.getter(#totalSets),
        returnValue: 0,
      ) as int);

  @override
  int get workSeconds => (super.noSuchMethod(
        Invocation.getter(#workSeconds),
        returnValue: 0,
      ) as int);

  @override
  int get restSeconds => (super.noSuchMethod(
        Invocation.getter(#restSeconds),
        returnValue: 0,
      ) as int);

  @override
  int get repsPerSet => (super.noSuchMethod(
        Invocation.getter(#repsPerSet),
        returnValue: 0,
      ) as int);

  @override
  int get currentRep => (super.noSuchMethod(
        Invocation.getter(#currentRep),
        returnValue: 0,
      ) as int);

  @override
  bool get isRunning => (super.noSuchMethod(
        Invocation.getter(#isRunning),
        returnValue: false,
      ) as bool);

  @override
  double get progress => (super.noSuchMethod(
        Invocation.getter(#progress),
        returnValue: 0.0,
      ) as double);

  @override
  int get completedSets => (super.noSuchMethod(
        Invocation.getter(#completedSets),
        returnValue: 0,
      ) as int);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> startWorkout(_i4.WorkoutConfig? config) =>
      (super.noSuchMethod(
        Invocation.method(
          #startWorkout,
          [config],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void pause() => super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resume() => super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stop() => super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
